#pragma once

#define MAX_CONNECTIONS 1

#define INIT_SPICE 20000
#define INIT_CSPICE 20000
#define INIT_ENERGY 2000
#define INIT_CENERGY 5000

#define HARVESTER_LP 600
#define HARVESTER_SPICE_COST 300
#define HARVESTER_SPICE_CAPACITY 50
#define HARVESTER_SPEED 2

#define TRIKE_LP 80
#define TRIKE_SPICE_COST 100
#define TRIKE_SPEED 4
#define TRIKE_ATTACK 2
#define TRIKE_RANGE 4

#define FREMEN_LP 50
#define FREMEN_SPICE_COST 100
#define FREMEN_SPEED 2
#define FREMEN_ATTACK 8
#define FREMEN_RANGE 3

#define INFANTRY_LP 50
#define INFANTRY_SPICE_COST 50
#define INFANTRY_SPEED 2
#define INFANTRY_ATTACK 2
#define INFANTRY_RANGE 3

#define SARDAUKAR_LP 80
#define SARDAUKAR_SPICE_COST 100
#define SARDAUKAR_SPEED 2
#define SARDAUKAR_ATTACK 10
#define SARDAUKAR_RANGE 3

#define TANK_LP 30
#define TANK_SPICE_COST 300
#define TANK_SPEED 3
#define TANK_ATTACK 7
#define TANK_RANGE 3

#define DEVASTATOR_LP 400
#define DEVASTATOR_SPICE_COST 400
#define DEVASTATOR_SPEED 2
#define DEVASTATOR_ATTACK 8
#define DEVASTATOR_RANGE 4

#define CONSTRUCTION_YARD_LP 3000
#define CONSTRUCTION_YARD_ENERGY 2000
#define CONSTRUCTION_YARD_SPICE 0
#define CONSTRUCTION_YARD_DIM_X 3
#define CONSTRUCTION_YARD_DIM_Y 3

#define AIR_TRAP_LP 500
#define AIR_TRAP_ENERGY 500
#define AIR_TRAP_SPICE 800
#define AIR_TRAP_DIM_X 3
#define AIR_TRAP_DIM_Y 3
#define AIR_TRAP_CAPACITY 500

#define BARRACK_LP 300
#define BARRACK_ENERGY -100
#define BARRACK_SPICE 300
#define BARRACK_DIM_X 2
#define BARRACK_DIM_Y 3

#define REFINERY_LP 1000
#define REFINERY_ENERGY -400
#define REFINERY_SPICE 500
#define REFINERY_DIM_X 3
#define REFINERY_DIM_Y 3
#define REFINERY_CAPACITY 5000

#define LIGHT_FACTORY_LP 500
#define LIGHT_FACTORY_ENERGY -500
#define LIGHT_FACTORY_SPICE 800
#define LIGHT_FACTORY_DIM_X 3
#define LIGHT_FACTORY_DIM_Y 3

#define HEAVY_FACTORY_LP 1500
#define HEAVY_FACTORY_ENERGY -800
#define HEAVY_FACTORY_SPICE 1500
#define HEAVY_FACTORY_DIM_X 4
#define HEAVY_FACTORY_DIM_Y 4

#define SILO_LP 200
#define SILO_ENERGY -100
#define SILO_SPICE 200
#define SILO_SPICE_CAPACITY 1000
#define SILO_DIM_X 1
#define SILO_DIM_Y 1

#define PALACE_LP 1000
#define PALACE_ENERGY -800
#define PALACE_SPICE 2000
#define PALACE_DIM_X 3
#define PALACE_DIM_Y 3

#define SAND_SPICE_FULL 1000
#define SAND_SPICE_SOME 500
#define SAND_SPICE_LITTLE 200
#define SAND_SPICE_EMPTY 0
